type = "about"
title = "About"

[profile]
research_interests = [
  "Behavioral and experimental economics",
  "Microeconomic theory",
  "Machine Learning"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "Welcome!"

# [[sections]]
# id = "research"
# type = "markdown"
# source = "research.md"
# title = "My Research"


[[sections]]
id = "featured_publications"
type = "publications"
title = "My Research"
filter = "selected"
limit = 5

# [[sections]]
# id = "news"
# type = "list"
# title = "News"
# source = "news.toml"

